### ISSUE TITLE
No module named

### ISSUE THREAD

**Issue by CarmenLexa** [andrew-ld/webgram#2]
thanks for your input, but i have this problem

File "F:\ProyectoPython\webgram\webgram\tools.py", line 5, in <module>   
    from pyrogram.api.functions.channels import GetMessages
ModuleNotFoundError: No module named 'pyrogram.api'

**Comment by CarmenLexa** [comment]
I made changes to from pyrogram.raw
now i have this other problem

Traceback (most recent call last):
   File "__main__.py", line 9, in <module>
     server = webgram.BareServer ()
   File "F: \ Python Project \ webgram \ webgram \ bare.py", line 58, in __init__
     session = pyrogram.session.Session (
   File "C: \ Python38 \ lib \ site-packages \ pyrogram \ session \ session.py", line 97, in __init__
     self.auth_key_id = sha1 (auth_key) .digest () [- 8:]
TypeError: object supporting the buffer API required

**Comment by Trongbach** [comment]
> thanks for your input, but i have this problem
> 
> File "F:\ProyectoPython\webgram\webgram\tools.py", line 5, in
> from pyrogram.api.functions.channels import GetMessages
> ModuleNotFoundError: No module named 'pyrogram.api'

Can you run this now? I got same problem,

**Comment by andrew-ld** [comment]
@Trongbach the project Is unmanteined

all webgram features have been improved in the new software:

https://github.com/andrew-ld/smart-tv-telegram

however you probably have another version of pyrogram, install the version defined on the requiremets file and it should work even if I do not recommend continuing to use webgram
